overrides:
  kysely: 0.28.17

allowBuilds:
  '@firebase/util': false
  '@sentry/cli': true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.14'
  - '@better-auth/drizzle-adapter@1.6.14'
  - '@better-auth/kysely-adapter@1.6.14'
  - '@better-auth/memory-adapter@1.6.14'
  - '@better-auth/mongo-adapter@1.6.14'
  - '@better-auth/prisma-adapter@1.6.14'
  - '@better-auth/telemetry@1.6.14'
  - better-auth@1.6.14
