import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          "1": "hsl(var(--chart-1))",
          "2": "hsl(var(--chart-2))",
          "3": "hsl(var(--chart-3))",
          "4": "hsl(var(--chart-4))",
          "5": "hsl(var(--chart-5))",
        },
        sidebar: {
          background: "hsl(var(--sidebar-background))",
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        primary: {
          DEFAULT: "var(--primary-color-500)",
          50: "var(--primary-color-50)",
          100: "var(--primary-color-100)",
          200: "var(--primary-color-200)",
          300: "var(--primary-color-300)",
          400: "var(--primary-color-400)",
          500: "var(--primary-color-500)",
          600: "var(--primary-color-600)",
          700: "var(--primary-color-700)",
          800: "var(--primary-color-800)",
          900: "var(--primary-color-900)",
          foreground: "#fff",
        },
        success: {
          DEFAULT: "var(--success-color-500)",
          50: "var(--success-color-50)",
          100: "var(--success-color-100)",
          200: "var(--success-color-200)",
          300: "var(--success-color-300)",
          400: "var(--success-color-400)",
          500: "var(--success-color-500)",
          600: "var(--success-color-600)",
          700: "var(--success-color-700)",
          800: "var(--success-color-800)",
          900: "var(--success-color-900)",
          foreground: "#fff",
        },
        warning: {
          DEFAULT: "var(--warning-color-500)",
          50: "var(--warning-color-50)",
          100: "var(--warning-color-100)",
          200: "var(--warning-color-200)",
          300: "var(--warning-color-300)",
          400: "var(--warning-color-400)",
          500: "var(--warning-color-500)",
          600: "var(--warning-color-600)",
          700: "var(--warning-color-700)",
          800: "var(--warning-color-800)",
          900: "var(--warning-color-900)",
          foreground: "#fff",
        },
        danger: {
          DEFAULT: "var(--danger-color-500)",
          50: "var(--danger-color-50)",
          100: "var(--danger-color-100)",
          200: "var(--danger-color-200)",
          300: "var(--danger-color-300)",
          400: "var(--danger-color-400)",
          500: "var(--danger-color-500)",
          600: "var(--danger-color-600)",
          700: "var(--danger-color-700)",
          800: "var(--danger-color-800)",
          900: "var(--danger-color-900)",
          foreground: "#fff",
        },
        secondary: {
          DEFAULT: "var(--secondary-color-500)",
          50: "var(--secondary-color-50)",
          100: "var(--secondary-color-100)",
          200: "var(--secondary-color-200)",
          300: "var(--secondary-color-300)",
          400: "var(--secondary-color-400)",
          500: "var(--secondary-color-500)",
          600: "var(--secondary-color-600)",
          700: "var(--secondary-color-700)",
          800: "var(--secondary-color-800)",
          900: "var(--secondary-color-900)",
          foreground: "#fff",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",

        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        info: {
          50: "#ecfdff",
          100: "#cef9ff",
          200: "#a3f2fe",
          300: "#64e6fc",
          400: "#0dcaf0",
          500: "#01b1d9",
          600: "#048db6",
          700: "#0b7193",
          800: "#135b77",
          900: "#144c65",
          950: "#073245",
          DEFAULT: "#0dcaf0",
          foreground: "#fff",
        },
        pending: {
          50: "#eef7ff",
          100: "#d8edff",
          200: "#b9e0ff",
          300: "#89ceff",
          400: "#52b3ff",
          500: "#2a91ff",
          600: "#0d6dfd",
          700: "#0c59e9",
          800: "#1148bc",
          900: "#144094",
          950: "#11285a",
          DEFAULT: "#0d6dfd",
          foreground: "#fff",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 10px)",
      },
    },
  },
  plugins: [tailwindcssAnimate],
} satisfies Config;
