import type { ApoloSipsProcedure, ApoloSipsSupplyType } from "./types";

export const ELECTRICITY_PS_COLUMNS = [
  "codigoEmpresaDistribuidora",
  "cups",
  "nombreEmpresaDistribuidora",
  "codigoPostalPS",
  "municipioPS",
  "codigoProvinciaPS",
  "fechaAltaSuministro",
  "codigoTarifaATREnVigor",
  "codigoTensionV",
  "potenciaMaximaBIEW",
  "potenciaMaximaAPMW",
  "codigoClasificacionPS",
  "codigoDisponibilidadICP",
  "tipoPerfilConsumo",
  "valorDerechosExtensionW",
  "valorDerechosAccesoW",
  "codigoPropiedadEquipoMedida",
  "codigoPropiedadICP",
  "potenciasContratadasEnWP1",
  "potenciasContratadasEnWP2",
  "potenciasContratadasEnWP3",
  "potenciasContratadasEnWP4",
  "potenciasContratadasEnWP5",
  "potenciasContratadasEnWP6",
  "fechaUltimoMovimientoContrato",
  "fechaUltimoCambioComercializador",
  "fechaLimiteDerechosReconocidos",
  "fechaUltimaLectura",
  "informacionImpagos",
  "importeDepositoGarantiaEuros",
  "tipoIdTitular",
  "esViviendaHabitual",
  "codigoComercializadora",
  "codigoTelegestion",
  "codigoFasesEquipoMedida",
  "codigoAutoconsumo",
  "codigoTipoContrato",
  "codigoPeriodicidadFacturacion",
  "codigoBIE",
  "fechaEmisionBIE",
  "fechaCaducidadBIE",
  "codigoAPM",
  "fechaEmisionAPM",
  "fechaCaducidadAPM",
  "relacionTransformacionIntensidad",
  "cnae",
  "codigoModoControlPotencia",
  "potenciaCGPW",
  "codigoDHEquipoDeMedida",
  "codigoAccesibilidadContador",
  "codigoPSContratable",
  "motivoEstadoNoContratable",
  "codigoTensionMedida",
  "codigoClaseExpediente",
  "codigoMotivoExpediente",
  "codigoTipoSuministro",
  "aplicacionBonoSocial",
] as const;

export const ELECTRICITY_CONSUMPTION_COLUMNS = [
  "cups",
  "fechaInicioMesConsumo",
  "fechaFinMesConsumo",
  "codigoTarifaATR",
  "consumoEnergiaActivaEnWhP1",
  "consumoEnergiaActivaEnWhP2",
  "consumoEnergiaActivaEnWhP3",
  "consumoEnergiaActivaEnWhP4",
  "consumoEnergiaActivaEnWhP5",
  "consumoEnergiaActivaEnWhP6",
  "consumoEnergiaReactivaEnVArhP1",
  "consumoEnergiaReactivaEnVArhP2",
  "consumoEnergiaReactivaEnVArhP3",
  "consumoEnergiaReactivaEnVArhP4",
  "consumoEnergiaReactivaEnVArhP5",
  "consumoEnergiaReactivaEnVArhP6",
  "potenciaDemandadaEnWP1",
  "potenciaDemandadaEnWP2",
  "potenciaDemandadaEnWP3",
  "potenciaDemandadaEnWP4",
  "potenciaDemandadaEnWP5",
  "potenciaDemandadaEnWP6",
  "codigoDHEquipoDeMedida",
  "codigoTipoLectura",
] as const;

export const GAS_PS_COLUMNS = [
  "codigoEmpresaDistribuidora",
  "nombreEmpresaDistribuidora",
  "cups",
  "codigoProvinciaPS",
  "desProvinciaPS",
  "codigoPostalPS",
  "municipioPS",
  "desmunicipioPS",
  "tipoViaPS",
  "viaPS",
  "numFincaPS",
  "portalPS",
  "escaleraPS",
  "pisoPS",
  "puertaPS",
  "codigoPresion",
  "codigoPeajeEnVigor",
  "caudalMaximoDiarioEnWh",
  "caudalHorarioEnWh",
  "derechoTUR",
  "fechaUltimaInspeccion",
  "codigoResultadoInspeccion",
  "tipoPerfilConsumo",
  "codigoContador",
  "calibreContador",
  "tipoContador",
  "propiedadEquipoMedida",
  "codigoTelemedida",
  "fechaUltimoMovimientoContrato",
  "fechaUltimoCambioComercializador",
  "informacionImpagos",
  "idTipoTitular",
  "idTitular",
  "nombreTitular",
  "apellido1Titular",
  "apellido2Titular",
  "codigoProvinciaTitular",
  "desProvinciaTitular",
  "codigoPostalTitular",
  "municipioTitular",
  "desMunicipioTitular",
  "tipoViaTitular",
  "viaTitular",
  "numFincaTitular",
  "portalTitular",
  "escaleraTitular",
  "pisoTitular",
  "puertaTitular",
  "esViviendaHabitual",
  "cnae",
  "tipoCorrector",
  "codigoAccesibilidadContador",
  "conectadoPlantaSatelite",
  "pctd",
  "presionMedida",
] as const;

export const GAS_CONSUMPTION_COLUMNS = [
  "cups",
  "fechaInicioMesConsumo",
  "fechaFinMesConsumo",
  "codigoTarifaPeaje",
  "consumoEnWhP1",
  "consumoEnWhP2",
  "caudalMedioEnWhdia",
  "caudaMinimoDiario",
  "caudaMaximoDiario",
  "porcentajeConsumoNocturno",
  "codigoTipoLectura",
] as const;

export const NUMERIC_APOLO_SIPS_COLUMNS = new Set<string>([
  "potenciaMaximaBIEW",
  "potenciaMaximaAPMW",
  "valorDerechosExtensionW",
  "valorDerechosAccesoW",
  "potenciasContratadasEnWP1",
  "potenciasContratadasEnWP2",
  "potenciasContratadasEnWP3",
  "potenciasContratadasEnWP4",
  "potenciasContratadasEnWP5",
  "potenciasContratadasEnWP6",
  "importeDepositoGarantiaEuros",
  "relacionTransformacionIntensidad",
  "potenciaCGPW",
  "consumoEnergiaActivaEnWhP1",
  "consumoEnergiaActivaEnWhP2",
  "consumoEnergiaActivaEnWhP3",
  "consumoEnergiaActivaEnWhP4",
  "consumoEnergiaActivaEnWhP5",
  "consumoEnergiaActivaEnWhP6",
  "consumoEnergiaReactivaEnVArhP1",
  "consumoEnergiaReactivaEnVArhP2",
  "consumoEnergiaReactivaEnVArhP3",
  "consumoEnergiaReactivaEnVArhP4",
  "consumoEnergiaReactivaEnVArhP5",
  "consumoEnergiaReactivaEnVArhP6",
  "potenciaDemandadaEnWP1",
  "potenciaDemandadaEnWP2",
  "potenciaDemandadaEnWP3",
  "potenciaDemandadaEnWP4",
  "potenciaDemandadaEnWP5",
  "potenciaDemandadaEnWP6",
  "caudalMaximoDiarioEnWh",
  "caudalHorarioEnWh",
  "pctd",
  "presionMedida",
  "consumoEnWhP1",
  "consumoEnWhP2",
  "caudalMedioEnWhdia",
  "caudaMinimoDiario",
  "caudaMaximoDiario",
  "porcentajeConsumoNocturno",
]);

export function getExpectedApoloSipsColumns(
  procedure: ApoloSipsProcedure,
  supplyType: ApoloSipsSupplyType,
): readonly string[] {
  if (procedure === "PS" && supplyType === "ELECTRICIDAD") {
    return ELECTRICITY_PS_COLUMNS;
  }

  if (procedure === "CONSUMOS" && supplyType === "ELECTRICIDAD") {
    return ELECTRICITY_CONSUMPTION_COLUMNS;
  }

  if (procedure === "PS" && supplyType === "GAS") {
    return GAS_PS_COLUMNS;
  }

  return GAS_CONSUMPTION_COLUMNS;
}
